//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessCenterManagement.WebApp.Views.Home.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FitnessCenterManagement.WebApp.Views.Home.Resources.HomeRes", typeof(HomeRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FITPRO - is a team of the professionals, who work in the field of health services for over 10 years. We are the first who work with men and women of all ages and any skill: from youngest children to the elder ones. We are preferred by professional athletes and those who are taking the first steps towards a healthy lifestyle. Our range of services includes more than 25 wellness areas. We are preferred by the largest and most successful corporate clients..
        /// </summary>
        public static string ApplicationDescription {
            get {
                return ResourceManager.GetString("ApplicationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As you are already registered and signed in, you have full access to our services. Thanks:).
        /// </summary>
        public static string AuthedAdviceText {
            get {
                return ResourceManager.GetString("AuthedAdviceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,.
        /// </summary>
        public static string AuthedHelloLine {
            get {
                return ResourceManager.GetString("AuthedHelloLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We enjoy seeing you among us.
        /// </summary>
        public static string EnjoySeeingYouAmongUsPhrase {
            get {
                return ResourceManager.GetString("EnjoySeeingYouAmongUsPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join us!.
        /// </summary>
        public static string JoinUsButton {
            get {
                return ResourceManager.GetString("JoinUsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, sign in your account or create a new one due to registered user has increased capabilities, for example, to customer&apos;s personal features. Thanks:).
        /// </summary>
        public static string NotAuthedAdviceText {
            get {
                return ResourceManager.GetString("NotAuthedAdviceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, dear visitor!.
        /// </summary>
        public static string NotAuthedHelloLine {
            get {
                return ResourceManager.GetString("NotAuthedHelloLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIS IS A LIFESTYLE. THERE IS NO FINISH LINE!.
        /// </summary>
        public static string Phrase1 {
            get {
                return ResourceManager.GetString("Phrase1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP WISHING, START DOING!.
        /// </summary>
        public static string Phrase2 {
            get {
                return ResourceManager.GetString("Phrase2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DON&apos;T STOP WHEN IT HURTS, STOP WHEN YOU&apos;RE DONE!.
        /// </summary>
        public static string Phrase3 {
            get {
                return ResourceManager.GetString("Phrase3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORKING OUT IS A REWARD NOT A PUNISHMENT!.
        /// </summary>
        public static string Phrase4 {
            get {
                return ResourceManager.GetString("Phrase4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string ProfileBtn {
            get {
                return ResourceManager.GetString("ProfileBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still not with us?.
        /// </summary>
        public static string StillNotWithUsPhrase {
            get {
                return ResourceManager.GetString("StillNotWithUsPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVAILABILITY, CONVENIENCE, QUALITY OF SERVICES, BEST CONDITIONS AND EQUIPMENT ARE OUR MAIN GOALS!.
        /// </summary>
        public static string TaskDescription {
            get {
                return ResourceManager.GetString("TaskDescription", resourceCulture);
            }
        }
    }
}
