//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessCenterManagement.WebApp.Views.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedStringRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedStringRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FitnessCenterManagement.WebApp.Views.Shared.Resources.SharedStringRes", typeof(SharedStringRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abonements.
        /// </summary>
        public static string AbonementsBtn {
            get {
                return ResourceManager.GetString("AbonementsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitness center.
        /// </summary>
        public static string AboutFitnessCenterBtn {
            get {
                return ResourceManager.GetString("AboutFitnessCenterBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string AboutUsBtn {
            get {
                return ResourceManager.GetString("AboutUsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative.
        /// </summary>
        public static string AdminFunctional {
            get {
                return ResourceManager.GetString("AdminFunctional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIT.
        /// </summary>
        public static string ApplicationNameHalfOne {
            get {
                return ResourceManager.GetString("ApplicationNameHalfOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRO.
        /// </summary>
        public static string ApplicationNameHalfTwo {
            get {
                return ResourceManager.GetString("ApplicationNameHalfTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string AttentionWord {
            get {
                return ResourceManager.GetString("AttentionWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string ChangeText {
            get {
                return ResourceManager.GetString("ChangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose....
        /// </summary>
        public static string ChooseDropdownHint {
            get {
                return ResourceManager.GetString("ChooseDropdownHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Republic of Belarus, 
        ///Gomel, Rechitsky prospect, 135.
        /// </summary>
        public static string ContactAddress {
            get {
                return ResourceManager.GetString("ContactAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support@fitpro.by.
        /// </summary>
        public static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string ContactFooterLabel {
            get {
                return ResourceManager.GetString("ContactFooterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 (123) 456 789 123.
        /// </summary>
        public static string ContactPhone {
            get {
                return ResourceManager.GetString("ContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 (000) 112 233 456.
        /// </summary>
        public static string ContactPhone2 {
            get {
                return ResourceManager.GetString("ContactPhone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateBtn {
            get {
                return ResourceManager.GetString("CreateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        public static string CurrencySymbol {
            get {
                return ResourceManager.GetString("CurrencySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer categoeries.
        /// </summary>
        public static string CustomerCategoriesBtn {
            get {
                return ResourceManager.GetString("CustomerCategoriesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteBtn {
            get {
                return ResourceManager.GetString("DeleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditBtn {
            get {
                return ResourceManager.GetString("EditBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitness events.
        /// </summary>
        public static string EventsBtn {
            get {
                return ResourceManager.GetString("EventsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricelist.
        /// </summary>
        public static string FullPriceListFooterBtn {
            get {
                return ResourceManager.GetString("FullPriceListFooterBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string GoBackBtn {
            get {
                return ResourceManager.GetString("GoBackBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogInHeaderBtn {
            get {
                return ResourceManager.GetString("LogInHeaderBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOutHeaderBtn {
            get {
                return ResourceManager.GetString("LogOutHeaderBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty programs.
        /// </summary>
        public static string LoyaltyProgramsBtn {
            get {
                return ResourceManager.GetString("LoyaltyProgramsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage reviews....
        /// </summary>
        public static string ManageReviewsBtn {
            get {
                return ResourceManager.GetString("ManageReviewsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string MenuFooterLabel {
            get {
                return ResourceManager.GetString("MenuFooterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string MyProfileHeaderBtn {
            get {
                return ResourceManager.GetString("MyProfileHeaderBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainers.
        /// </summary>
        public static string OurTrainersBtn {
            get {
                return ResourceManager.GetString("OurTrainersBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterHeaderBtn {
            get {
                return ResourceManager.GetString("RegisterHeaderBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string ReportsBtn {
            get {
                return ResourceManager.GetString("ReportsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string ReturnAfterErrorBtn {
            get {
                return ResourceManager.GetString("ReturnAfterErrorBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string ReviewsBtn {
            get {
                return ResourceManager.GetString("ReviewsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveBtnValue {
            get {
                return ResourceManager.GetString("SaveBtnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules.
        /// </summary>
        public static string SchedulesBtn {
            get {
                return ResourceManager.GetString("SchedulesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchBtn {
            get {
                return ResourceManager.GetString("SearchBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string ServicesBtn {
            get {
                return ResourceManager.GetString("ServicesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get connected with us on social networks.
        /// </summary>
        public static string SocialsGetConnectedText {
            get {
                return ResourceManager.GetString("SocialsGetConnectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specializations.
        /// </summary>
        public static string SpecializationBtn {
            get {
                return ResourceManager.GetString("SpecializationBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For clients.
        /// </summary>
        public static string ToClientsLabel {
            get {
                return ResourceManager.GetString("ToClientsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateBtn {
            get {
                return ResourceManager.GetString("UpdateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UsersBtn {
            get {
                return ResourceManager.GetString("UsersBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venues.
        /// </summary>
        public static string VenuesBtn {
            get {
                return ResourceManager.GetString("VenuesBtn", resourceCulture);
            }
        }
    }
}
