//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessCenterManagement.WebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JqueryTableStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JqueryTableStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FitnessCenterManagement.WebApp.Resources.JqueryTableStrings", typeof(JqueryTableStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : activate to sort column ascending.
        /// </summary>
        public static string ActivateAscending {
            get {
                return ResourceManager.GetString("ActivateAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : activate to sort column descending.
        /// </summary>
        public static string ActivateDescending {
            get {
                return ResourceManager.GetString("ActivateDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available in table.
        /// </summary>
        public static string EmptyTableString {
            get {
                return ResourceManager.GetString("EmptyTableString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string FirstString {
            get {
                return ResourceManager.GetString("FirstString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing 0 to 0 of 0 entries.
        /// </summary>
        public static string InfoEmptyString {
            get {
                return ResourceManager.GetString("InfoEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching records found.
        /// </summary>
        public static string InfoFilteredString {
            get {
                return ResourceManager.GetString("InfoFilteredString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing _START_ to _END_ of _TOTAL_ entries.
        /// </summary>
        public static string InfoString {
            get {
                return ResourceManager.GetString("InfoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string LastString {
            get {
                return ResourceManager.GetString("LastString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _MENU_ entries.
        /// </summary>
        public static string LengthMenuString {
            get {
                return ResourceManager.GetString("LengthMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingString {
            get {
                return ResourceManager.GetString("LoadingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NextString {
            get {
                return ResourceManager.GetString("NextString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string PreviousString {
            get {
                return ResourceManager.GetString("PreviousString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string ProcessingString {
            get {
                return ResourceManager.GetString("ProcessingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchString {
            get {
                return ResourceManager.GetString("SearchString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching records found.
        /// </summary>
        public static string ZeroRecordsString {
            get {
                return ResourceManager.GetString("ZeroRecordsString", resourceCulture);
            }
        }
    }
}
